const CLASSES = {
  EVERYONE: "EVERYONE",
  DEATHKNIGHT: "DEATHKNIGHT",
  DEMONHUNTER: "DEMONHUNTER",
  DRUID: "DRUID",
  EVOKER: "EVOKER",
  HUNTER: "HUNTER",
  MAGE: "MAGE",
  MONK: "MONK",
  PALADIN: "PALADIN",
  PRIEST: "PRIEST",
  ROGUE: "ROGUE",
  SHAMAN: "SHAMAN",
  WARLOCK: "WARLOCK",
  WARRIOR: "WARRIOR",
};

export default CLASSES;
